#ifndef DEFINES_H
#define DEFINES_H

#define SCREEN_WIDTH 1280
#define SCREEN_HEIGHT 720

#define SHIP_VELOCITY 10;
#define BULLET_VELOCITY 20;

const int MAX_BULLET_COUNT = 3;

const int SLOW_ASTEROID_VELOCITY = 7;
const int MEDIUM_ASTEROID_VELOCITY = 20;
const int FAST_ASTEROID_VELOCITY = 35;
const int SUPERFAST_ASTEROID_VELOCITY = 50;
const int ASTEROID_VELOCITY[4] = {SLOW_ASTEROID_VELOCITY, MEDIUM_ASTEROID_VELOCITY, FAST_ASTEROID_VELOCITY, SUPERFAST_ASTEROID_VELOCITY};

#endif // DEFINES_H
